### PR TITLE
Tools setup

### PR DESCRIPTION
**Pull request by KyleStach1678**
Initial setup of all of the tools that we need to build code, including an external WORKSPACE dependency on our third party library repository.

### CODE REVIEW

**Comment by donald-pinckney** [comment]
Approve 👍

**Comment by donald-pinckney** [comment]
Re-approve 👍.  The script works well, and I feel this is the cleanest workflow possible for this. I'm interested to try it out with offseason.

**Comment by KyleStach1678** [comment]
Oops - that most recent push was accidental and was not meant to be included in this PR. It doesn't really have an impact for this PR as it is a part of the tools setup, but we should have a way of keeping this from happening in the future. Maybe have people make a separate branch for each PR, like tools-setup_pr?

**Comment by donald-pinckney** [comment]
Perhaps yeah. Though I don't want to add too many branches for people to keep track of, especially for new people.

**Comment by steampunc** [comment]
I'm a little confused about a better way to do that though, because it seems that any new commits to a branch add to the previous PR. Looking around on the internet, it looks like the only solution is to have people make separate branches, but I agree that seems messy.

**Comment by WesleyAC** [comment]
Approve :shipit:

**Pull request merged**
